import {
  Classroom,
  ClassroomDetail,
  TimetableSlot,
  Announcement,
  Resource,
  AcademicEvent,
} from '../types';

export const INITIAL_CLASSROOMS: ClassroomDetail[] = [
  {
    id: 1,
    name: 'CSE - A',
    section: 'A',
    department: 'CSE',
    year: 2,
    semester: 3,
    capacity: 120,
    studentCount: 114,
    academicYear: '2024-2025',
    advisorName: 'Dr. Sarah Müller',
    advisorEmail: 's.muller@bauhaus.edu',
    roomNumber: 'Hall C',
    syllabusProgress: 75,
    totalLecturesToday: 3,
    pendingGrading: 42,
  },
  {
    id: 2,
    name: 'CSE - B',
    section: 'B',
    department: 'CSE',
    year: 2,
    semester: 3,
    capacity: 120,
    studentCount: 108,
    academicYear: '2024-2025',
    advisorName: 'Prof. J. Albers',
    advisorEmail: 'j.albers@bauhaus.edu',
    roomNumber: 'Rm 301',
    syllabusProgress: 68,
    totalLecturesToday: 2,
    pendingGrading: 19,
  },
  {
    id: 3,
    name: 'ECE - Final Year',
    section: 'A',
    department: 'ECE',
    year: 4,
    semester: 7,
    capacity: 80,
    studentCount: 76,
    academicYear: '2024-2025',
    advisorName: 'Dr. K. Chen',
    advisorEmail: 'k.chen@bauhaus.edu',
    roomNumber: 'Lab 4',
    syllabusProgress: 82,
    totalLecturesToday: 4,
    pendingGrading: 35,
  },
  {
    id: 4,
    name: 'Mechanical - Sophomores',
    section: 'A',
    department: 'MECH',
    year: 2,
    semester: 4,
    capacity: 90,
    studentCount: 88,
    academicYear: '2024-2025',
    advisorName: 'Prof. P. Klee',
    advisorEmail: 'p.klee@bauhaus.edu',
    roomNumber: 'Studio 2',
    syllabusProgress: 60,
    totalLecturesToday: 3,
    pendingGrading: 28,
  },
];

export const INITIAL_TIMETABLE: TimetableSlot[] = [
  {
    id: 1,
    classroomId: 1,
    day: 'MON',
    startTime: '09:00:00',
    endTime: '10:30:00',
    subject: 'Data Structures & Algorithms',
    subjectCode: 'CS-301',
    facultyId: 101,
    facultyName: 'Dr. Sarah Müller',
    roomNumber: 'Hall C (Capacity: 120)',
    type: 'LECTURE',
    isUpcoming: false,
  },
  {
    id: 2,
    classroomId: 1,
    day: 'MON',
    startTime: '11:30:00',
    endTime: '13:00:00',
    subject: 'Advanced Machine Learning',
    subjectCode: 'CS-405',
    facultyId: 102,
    facultyName: 'Prof. J. Albers',
    roomNumber: 'Lab 4 (Requires Setup)',
    type: 'LAB',
    isUpcoming: true,
  },
  {
    id: 3,
    classroomId: 1,
    day: 'MON',
    startTime: '14:00:00',
    endTime: '15:30:00',
    subject: 'Curriculum Review Meeting',
    subjectCode: 'DEPT',
    facultyId: 103,
    facultyName: 'Admin Committee',
    roomNumber: 'Admin Block, Room 201',
    type: 'SEMINAR',
  },
  {
    id: 4,
    classroomId: 1,
    day: 'TUE',
    startTime: '08:00:00',
    endTime: '09:30:00',
    subject: 'Color Theory & UI Synthesis',
    subjectCode: 'DS-201',
    facultyId: 104,
    facultyName: 'Prof. P. Klee',
    roomNumber: 'Studio 2',
    type: 'LAB',
  },
  {
    id: 5,
    classroomId: 1,
    day: 'TUE',
    startTime: '10:00:00',
    endTime: '11:30:00',
    subject: 'Operating Systems & Concurrency',
    subjectCode: 'OS-301',
    facultyId: 101,
    facultyName: 'Dr. Sarah Müller',
    roomNumber: 'Room 201',
    type: 'LECTURE',
  },
  {
    id: 6,
    classroomId: 1,
    day: 'WED',
    startTime: '08:00:00',
    endTime: '09:30:00',
    subject: 'Design Systems & Bauhaus Form',
    subjectCode: 'DES-402',
    facultyId: 102,
    facultyName: 'Prof. J. Albers',
    roomNumber: 'Rm 402',
    type: 'LECTURE',
    hasConflict: false,
  },
  {
    id: 7,
    classroomId: 1,
    day: 'THU',
    startTime: '10:00:00',
    endTime: '11:30:00',
    subject: 'Advanced Typography & Grid Layouts',
    subjectCode: 'TYP-302',
    facultyId: 102,
    facultyName: 'Prof. J. Albers',
    roomNumber: 'Rm 301',
    type: 'LECTURE',
  },
  {
    id: 8,
    classroomId: 1,
    day: 'FRI',
    startTime: '08:00:00',
    endTime: '09:30:00',
    subject: 'Material Studies & Architectural Form',
    subjectCode: 'MAT-101',
    facultyId: 101,
    facultyName: 'Dr. Sarah Müller',
    roomNumber: 'Lab A',
    type: 'SEMINAR',
  },
  {
    id: 9,
    classroomId: 1,
    day: 'FRI',
    startTime: '14:00:00',
    endTime: '15:30:00',
    subject: 'Database Management Systems',
    subjectCode: 'DBMS-402',
    facultyId: 105,
    facultyName: 'Dr. K. Chen',
    roomNumber: 'Hall B',
    type: 'LECTURE',
  },
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 1,
    classroomId: null,
    department: 'CSE',
    title: 'Mandatory Server Maintenance & System Downtime Scheduled for Weekend',
    body: 'Please be advised that the main university servers will undergo critical infrastructure upgrades this coming weekend. Access to the Learning Management System, Student Portal, and faculty email servers will be intermittent from Saturday 10:00 PM to Sunday 06:00 AM. Ensure all grades and crucial documents are saved locally before this window.',
    type: 'DEPARTMENT',
    postedBy: 'Admin IT Support',
    authorRole: 'Infrastructure Team',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCv3wy29AjySfG9c5bGpgVh7T7SsIGFWPIaQ19AHmEPQlYCUjt_Y19ObK0o5GC_WtM4DNfNbaD824pwe5hB1vGK1kYwRpnLSUERQ9dnbkmD_ZPloRDX573RCCn1SSi3v3Mqq5bWCRdUc_j_i2hAQ8Y8pCwI88ggUqRHD_Of2-pn8YrCApYymfDCTEOu8R3IjiGOFWl28dGRb4Ey_s6fENr8zvBVtcgu6scTcXmN6kRl_5xsSmHV5NCt',
    createdAt: '2026-08-27T07:00:00',
    urgent: true,
  },
  {
    id: 2,
    classroomId: 1,
    department: 'CSE',
    title: 'Updated Reading List for Module 4: Advanced Data Structures',
    body: 'I have uploaded a revised syllabus for Module 4 to the resources folder. We will be skipping chapter 7 in the primary textbook and instead focusing on the newly attached PDF regarding non-linear graph traversal algorithms. Please review this material before Thursday\'s lecture.',
    type: 'SECTION',
    postedBy: 'Dr. Sarah Müller',
    authorRole: 'Course Instructor',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuChWb8trhqoMRQI66iS79xnX_Mx8Po1grc3Mb2t_G2Fw-CQA-_OrVl9OeZLbXe-95_dDYKr53tkcnmddiIQx1RfK9trdXYNE9S_5Nur-juJZ4S_-bqVDXe72pbgeVi9ZVIDq-NToMq2apDcC_dk0-ZuX0XfWRKbDUrK4pAaPVDMLzz3yrVo8fxxG5y-8BWUAojzRorjIUwykN_XVdMF6hgKYJ-roYAOtgLghGlhL8AcF3-o-3Tgx75S',
    createdAt: '2026-08-26T14:30:00',
    attachmentName: 'Mod4_Graph_Algos.pdf',
    attachmentSize: '2.4 MB',
    attachmentUrl: '#',
  },
  {
    id: 3,
    classroomId: null,
    department: 'GENERAL',
    title: 'Annual Design Thinking Symposium Registration Now Open',
    body: 'Join us for the 5th Annual Bauhaus Design Thinking Symposium. This year\'s theme focuses on integrating geometric functionalism with modern digital interfaces. Guest speakers include industry leaders from top tech firms. Early bird registration ends next Friday.',
    type: 'GENERAL',
    postedBy: 'Events Committee',
    authorRole: 'Campus Life',
    createdAt: '2026-08-25T11:15:00',
  },
  {
    id: 4,
    classroomId: null,
    department: 'CSE',
    title: 'Revised Academic Calendar Published for Fall Semester',
    body: 'Please note the changes in the mid-semester break dates as per the new university directive. Mid-term examination blocks are moved forward by three academic working days.',
    type: 'DEPARTMENT',
    postedBy: 'HOD Office',
    authorRole: 'Department Head',
    createdAt: '2026-08-25T09:00:00',
  },
  {
    id: 5,
    classroomId: null,
    department: 'GENERAL',
    title: 'New IEEE Journal & Digital Library Access Active',
    body: 'Faculty members and students can now access the expanded IEEE Xplore digital library using their campus single sign-on credentials.',
    type: 'GENERAL',
    postedBy: 'Library Services',
    authorRole: 'Academic Resource Desk',
    createdAt: '2026-08-24T16:00:00',
  },
];

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 1,
    classroomId: 1,
    title: 'Process Synchronization & Deadlocks',
    description: 'Detailed notes covering Mutexes, Semaphores, Monitors, and Banker\'s Algorithm with code examples.',
    subject: 'OS-301',
    type: 'NOTES',
    fileName: 'OS_Unit2_Synchronization.pdf',
    fileSize: '4.2 MB',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'Dr. Sarah Müller',
    createdAt: '2026-08-20T10:00:00',
    updatedAt: '2026-08-22T14:00:00',
  },
  {
    id: 2,
    classroomId: 1,
    title: 'Normal Forms and Dependency Preservation',
    description: 'Lecture slides for week 5 covering 1NF through BCNF, closure properties, and lossless decomposition algorithms.',
    subject: 'DBMS-402',
    type: 'PPT',
    fileName: 'DBMS_Normalization_Slides.pptx',
    fileSize: '12.8 MB',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'Dr. K. Chen',
    createdAt: '2026-08-18T11:30:00',
    updatedAt: '2026-08-21T09:15:00',
  },
  {
    id: 3,
    classroomId: 1,
    title: 'Implementation of K-Means Clustering',
    description: 'Problem set 3: Build K-Means from scratch in Python and analyze convergence rates on high-dimensional datasets.',
    subject: 'ML-505',
    type: 'ASSIGNMENT',
    fileName: 'Assignment3_KMeans_Starter.zip',
    fileSize: '1.1 MB',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'Prof. J. Albers',
    createdAt: '2026-08-16T15:45:00',
    updatedAt: '2026-08-19T17:00:00',
  },
  {
    id: 4,
    classroomId: 1,
    title: 'TCP Congestion Control Mechanisms',
    description: 'Video recording of lecture 12. Covers Slow Start, Congestion Avoidance, Fast Retransmit, and Fast Recovery algorithms.',
    subject: 'CN-401',
    type: 'RECORDED_LECTURE',
    fileName: 'CN_Lecture12_CongestionControl.mp4',
    fileSize: '245 MB',
    fileUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    uploadedBy: 'Dr. Sarah Müller',
    createdAt: '2026-08-15T09:00:00',
    updatedAt: '2026-08-15T12:00:00',
  },
  {
    id: 5,
    classroomId: 1,
    title: 'Operating Systems: Three Easy Pieces (Reference Edition)',
    description: 'Supplemental reference readings for virtual memory, page replacement algorithms, and multi-level page tables.',
    subject: 'OS-301',
    type: 'REFERENCE',
    fileName: 'OSTEP_VirtualMemory_Reference.pdf',
    fileSize: '8.4 MB',
    fileUrl: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
    uploadedBy: 'Dr. Sarah Müller',
    createdAt: '2026-08-10T14:20:00',
    updatedAt: '2026-08-12T16:00:00',
  },
];

export const INITIAL_EVENTS: AcademicEvent[] = [
  {
    id: 1,
    classroomId: 1,
    title: 'Midterm Examination: Quantum Mechanics & Computation',
    description: 'Covers Units 1 through 3. Closed-book written examination with scientific calculator permitted.',
    type: 'TEST',
    subject: 'PHY-301 • Advanced Physics',
    eventDateTime: '2026-08-27T14:00:00',
    durationMinutes: 120,
    venue: 'Hall B',
    syncToCalendar: true,
    isUpcoming: true,
    isUrgent: true,
  },
  {
    id: 2,
    classroomId: 1,
    title: 'Research Methodology Proposal Submission',
    description: 'Upload PDF proposal with literature review and experimental design schema.',
    type: 'ASSIGNMENT',
    subject: 'RES-500 • Graduate Seminar',
    eventDateTime: '2026-08-27T23:59:00',
    durationMinutes: 0,
    venue: 'Online Submission Portal',
    syncToCalendar: true,
    isUpcoming: true,
    isUrgent: true,
  },
  {
    id: 3,
    classroomId: 1,
    title: 'AI Ethics & Algorithmic Fairness Group Defense',
    description: 'Group presentation evaluating bias mitigation in large-scale classification pipelines.',
    type: 'PRESENTATION',
    subject: 'CS-405 • Machine Learning',
    eventDateTime: '2026-08-28T09:00:00',
    durationMinutes: 45,
    venue: 'Seminar Rm 3',
    syncToCalendar: true,
    isUpcoming: true,
  },
  {
    id: 4,
    classroomId: 1,
    title: 'Literature & Critical Theory Oral Exam',
    description: 'Individual 30-minute viva covering modern aesthetics and architectural prose.',
    type: 'VIVA',
    subject: 'ENG-201 • Humanities',
    eventDateTime: '2026-08-28T11:30:00',
    durationMinutes: 30,
    venue: 'Virtual Link / Studio 2',
    syncToCalendar: false,
    isUpcoming: true,
  },
  {
    id: 5,
    classroomId: 1,
    title: 'Faculty Guest Lecture: Dr. Chen on High-Performance DBs',
    description: 'Department-wide technical keynote on distributed consensus in LSM-tree architectures.',
    type: 'OTHER',
    subject: 'Dept. Wide Keynote',
    eventDateTime: '2026-08-29T15:00:00',
    durationMinutes: 90,
    venue: 'Main Auditorium',
    syncToCalendar: true,
    isUpcoming: true,
  },
  {
    id: 6,
    classroomId: 1,
    title: 'Final Year Project Phase 1 Demonstrations',
    description: 'Evaluation committee walkthrough for semester milestones.',
    type: 'PRESENTATION',
    subject: 'CS-490 • Capstone',
    eventDateTime: '2026-09-05T10:00:00',
    durationMinutes: 180,
    venue: 'Panel 3 - Main Auditorium',
    syncToCalendar: true,
    isUpcoming: true,
  },
];
